/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PrivateUsersRouteImport } from './routes/_private/users'
import { Route as PrivateRequestsRouteImport } from './routes/_private/requests'
import { Route as PrivateObjectsRouteImport } from './routes/_private/objects'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateUsersRoute = PrivateUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateRequestsRoute = PrivateRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateObjectsRoute = PrivateObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => PrivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/objects': typeof PrivateObjectsRoute
  '/requests': typeof PrivateRequestsRoute
  '/users': typeof PrivateUsersRoute
  '/login': typeof PublicLoginRoute
  '/': typeof PrivateIndexRoute
}
export interface FileRoutesByTo {
  '/objects': typeof PrivateObjectsRoute
  '/requests': typeof PrivateRequestsRoute
  '/users': typeof PrivateUsersRoute
  '/login': typeof PublicLoginRoute
  '/': typeof PrivateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/objects': typeof PrivateObjectsRoute
  '/_private/requests': typeof PrivateRequestsRoute
  '/_private/users': typeof PrivateUsersRoute
  '/_public/login': typeof PublicLoginRoute
  '/_private/': typeof PrivateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/objects' | '/requests' | '/users' | '/login' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/objects' | '/requests' | '/users' | '/login' | '/'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/objects'
    | '/_private/requests'
    | '/_private/users'
    | '/_public/login'
    | '/_private/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/users': {
      id: '/_private/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateUsersRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/requests': {
      id: '/_private/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof PrivateRequestsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/objects': {
      id: '/_private/objects'
      path: '/objects'
      fullPath: '/objects'
      preLoaderRoute: typeof PrivateObjectsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateObjectsRoute: typeof PrivateObjectsRoute
  PrivateRequestsRoute: typeof PrivateRequestsRoute
  PrivateUsersRoute: typeof PrivateUsersRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateObjectsRoute: PrivateObjectsRoute,
  PrivateRequestsRoute: PrivateRequestsRoute,
  PrivateUsersRoute: PrivateUsersRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
